### ISSUE TITLE
add  Vassilios Mewes as lecturer

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/et2021uiuc#13]
Vassilios Mewes agreed to present an "Introduction to GR(M)HD" on July 28th (day 3) first two slots.

**Comment by mgracia22** [comment]
I added Vassilios, why the parenthesis in the M?, I didn't added but I can if there's a reason for that.

**Comment by rhaas80** [comment]
It's not clear if Vassili will cover magneto-hydro-dynamics or only hydro-dynamics. Either one is fine though.
