### ISSUE TITLE
add "tutorial help" and "setup help" sections

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/et2021uiuc#15]
we will offer set and tuturial help just before and just after each day of the school. These should be added as extra columns in the schedule following the Google sheet planning document.

**Comment by mgracia22** [comment]
Did you mean rows at the top and bottom of the schedule? I did it following the google sheet planning.

**Comment by rhaas80** [comment]
yes, those were the ones I had in mind. thank you.
