### ISSUE TITLE
deadline for abstract has passed

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/et2021uiuc#16]
abstract can longer be submitted. Thus:

* the abstract deadline enty on the front page should be replaced by "abstract submission has closed"
* the "we encourage presentationis" blurb on the registration page should be removed and replaced by a similar note. We cannot remove the abstract and title entries from the form since it required for speakers to (possibly) update them

@rhaas80 : draft some javascript / liquid code to generate lightning talk pages from csv export of website.

**Comment by mgracia22** [comment]
done
