### ISSUE TITLE
remove Antornios Tsokaros from list of lecturers

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/et2021uiuc#18]
Antonios won't be able to lecture unfortunately and should be removed from the list of lecturers

**Comment by mgracia22** [comment]
Removed.

**Comment by mgracia22** [comment]
Only for the lecturers list or also the talk? I removed and replaced for TBD. or do you mean to keep the title but the author to TBD.

**Comment by rhaas80** [comment]
We will have to find a replacement speaker for the talk, so the talk title could / should stay, only the name removed. We will have to find some way to ack' Antonios' effort in the about page I guess. Cannot list him as speaker but want to show his (temporary) involvement.

**Comment by rhaas80** [comment]
So  keep the title but the author to TBD.

**Comment by rhaas80** [comment]
swapped in Josh Faber in 1dd55d6
